services:
  - type: web
    name: ecotaggy
    env: java
    plan: free
    buildCommand: cd ecoTaggy-backend && sh ./mvnw -DskipTests package
    startCommand: sh ./start.sh
    healthCheckPath: /
    envVars:
      - key: JAVA_VERSION
        value: 21
